spring:
    application:
        name: spring-project-steganography-tool
    threads:
        virtual:
            enabled: true
    data:
        mongodb:
            uri: ${MONGODB_URI:mongodb://db-mongo:27017/stego}