spring:
    application:
        name: spring-project-steganography-tool
    threads:
        virtual:
            enabled: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    data:
        mongodb:
            uri: ${MONGODB_URI:mongodb://db-mongo:27017/stego}