spring:
    application:
        name: spring-project-steganography-tool
    threads:
        virtual:
            enabled: true
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    datasource:
        url: jdbc:mysql://db-mysql:3306/stego
        username: user
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
