spring:
    application:
        name: spring-project-steganography-tool
    threads:
        virtual:
            enabled: true
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    datasource:
        url: jdbc:mysql://db-mysql:3306/stego
        username: user
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true


app:
    storage:
        base-path: ${STORAGE_BASE_PATH}
    cleanup:
        enabled: true # Set to true to enable cleanup task
        initial-delay-ms: 60000 # 1 minute
        interval-ms: 120000  # 2 minutes
    stream:
        threshold-bytes: 1000000 # 1 MB cutoff for streaming vs in-memory processing
    extraction:
        temp-ttl-ms: 300000 # 5 minutes